server:
  port: 8000

ribbon:
    ReadTimeout:  5000
    ConnectTimeout: 5000

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://Eureka7001.com:7001/eureka, http://Eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-consumer-openfeign-order
