server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #从注册中心eureka回去注册路由，利用微服务实现动态路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PROVIDER-PAYMENT   #匹配后提供服务的路由地址
#          uri:lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/findPaymentById/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/**   #断言,路径相匹配的进行路由

        - id: payment_routh3
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/myRyle/lb   #断言,路径相匹配的进行路由
        - id: payment_routh4
          uri: https://news.baidu.com
          predicates:
          - Path=/internet/**   #断言,路径相匹配的进行路由


#向eureka服务注册中心注册自己
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
